version: '3.3'
services:
  nginx:
    image: nginx:alpine
    container_name: "nginx"
    # Add our nginx configuration
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - 80:80
    links:
      - backend:backend

  db:
    image: postgres:alpine
    container_name: "postgres"
    # Ports allows us to access the database directly
    # It should be disabled on production
    ports:
      - 5434:5432
    expose:
      - 5432
    # Setup the default user/pass
    environment:
      POSTGRES_DB: dreamescape
      POSTGRES_USER: dave
      POSTGRES_PASSWORD: bowman

  backend:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    container_name: "backend"
    restart: always
    links:
      - db:database
      - redis:localRedis
    volumes: 
      - ./:/var/www/
    env_file:
      - .env
    ports:
      - 8000:8000
    expose:
      - 8000
    user: root
    command: /bin/sh -c './docs/sphinx.sh & uwsgi --ini /var/www/app/uwsgi.ini --py-autoreload 1'

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379
    expose:
      - 6379

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "openapi"
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost/api
